var productName;
productName = "laptop";
// productName = 23;
console.log(productName);
var productPrice;
productPrice = 23;
// productPrice = "23";
console.log(productPrice);
var discountAvailable;
discountAvailable = true;
// discountAvailable = "true";
console.log(discountAvailable);
